// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fdceqriehyfjentvsjce.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkY2VxcmllaHlmamVudHZzamNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNzgzMDQsImV4cCI6MjA2NTY1NDMwNH0.8IKEVPtXljVH17VZ9tLlFYmMFrmnuc9XnPpAm4N6gXg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);